# Permalinks
permalink:           pretty

# Setup
title:               Lee Surkis
tagline:             A Beginner's Data Science Blog
url:                 http://leesurkis.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lee Surkis
  url:               https://instagram.com/leesurkis1
  email:             leesurkis@live.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/leesurkis

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
